# Generated by Django 4.0.1 on 2022-02-08 12:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=255)),
                ('privacy_policy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 8, 14, 53, 1, 985309))),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 8, 14, 53, 1, 985309))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contact me',
                'ordering': ['created_at'],
            },
        ),
    ]
