# Generated by Django 4.0.1 on 2022-02-16 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_api', '0005_alter_contact_created_at_alter_contact_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 16, 15, 23, 26, 455528)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 16, 15, 23, 26, 455528)),
        ),
    ]
