# Generated by Django 4.0.1 on 2022-03-01 07:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=100)),
                ('invoice_number', models.CharField(default='', max_length=15)),
                ('invoice_series', models.CharField(default='', max_length=15)),
                ('supplier_code', models.CharField(default='', max_length=5)),
                ('supplier_name', models.CharField(default='', max_length=255)),
                ('supplier_vat', models.BooleanField(default=False)),
                ('invoice_date', models.DateField(default=datetime.datetime(2022, 3, 1, 9, 54, 23, 809636))),
                ('invoice_due_date', models.DateField(default=datetime.datetime(2022, 3, 1, 9, 54, 23, 809636))),
                ('invoice_gross_value', models.IntegerField(default=0)),
                ('invoice_vat_value', models.IntegerField(default=0)),
                ('invoice_net_value', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 1, 9, 54, 23, 809636))),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 1, 9, 54, 23, 809636))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Facturi de Cumparare',
                'ordering': ['created_at'],
            },
        ),
    ]
