# Generated by Django 4.0.1 on 2022-03-01 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 1, 9, 55, 7, 575346)),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_due_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 1, 9, 55, 7, 575346)),
        ),
    ]
