# Generated by Django 4.0.1 on 2022-02-08 10:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0006_alter_category_options_remove_category_posts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='body',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='created',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='title',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='blog_category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='blog_api.category'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='blog_subcategory_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='blog_subcategory_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='blog_subcategory_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='blog_subcategory_short_description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='blog_subcategory_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 8, 12, 16, 25, 113534)),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 8, 12, 16, 25, 113534)),
        ),
        migrations.AlterField(
            model_name='category',
            name='blog_subcategories',
            field=models.ManyToManyField(related_name='subcategories', to='blog_api.Subcategory'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 8, 12, 16, 25, 112534)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 8, 12, 16, 25, 112534)),
        ),
    ]
