# Generated by Django 4.0.1 on 2022-02-08 10:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_api', '0008_remove_post_owner_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 8, 12, 44, 26, 659918)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 8, 12, 44, 26, 659918)),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 8, 12, 44, 26, 660918)),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 8, 12, 44, 26, 660918)),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_article_author', models.CharField(default='', max_length=100)),
                ('blog_article_time', models.IntegerField(default='')),
                ('blog_article_title', models.CharField(default='', max_length=100)),
                ('blog_article_short_description', models.CharField(default='', max_length=255)),
                ('blog_article_content', models.TextField(default='')),
                ('blog_article_path', models.CharField(default='', max_length=255)),
                ('blog_article_is_active', models.BooleanField(default=False)),
                ('blog_article_rating_system', models.IntegerField(default='')),
                ('blog_article_likes', models.IntegerField(default='')),
                ('blog_article_dislikes', models.IntegerField(default='')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 8, 12, 44, 26, 661917))),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 8, 12, 44, 26, 661917))),
                ('blog_subcategory_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog_api.subcategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Articles',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='subcategory',
            name='blog_articles',
            field=models.ManyToManyField(related_name='articles', to='blog_api.Article'),
        ),
    ]
