# Generated by Django 4.0.1 on 2022-02-16 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_api', '0004_alter_newsletter_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 16, 15, 23, 26, 463527)),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 16, 15, 23, 26, 463527)),
        ),
    ]
