# Generated by Django 4.0.1 on 2022-02-28 16:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acc_suppliers_and_clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 28, 18, 12, 58, 759951)),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 28, 18, 12, 58, 759951)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 28, 18, 12, 58, 756701)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 28, 18, 12, 58, 756701)),
        ),
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(default='', max_length=13)),
                ('name', models.CharField(default='', max_length=255)),
                ('type', models.CharField(default='', max_length=1)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 28, 18, 12, 58, 760993))),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 28, 18, 12, 58, 760993))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_of_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['created_at'],
            },
        ),
    ]
