# Generated by Django 4.0.1 on 2022-02-28 16:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acc_suppliers_and_clients', '0002_alter_client_created_at_alter_client_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartofaccount',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Plan de conturi'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Clienti'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Furnizori'},
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 28, 18, 33, 42, 442759)),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 28, 18, 33, 42, 442759)),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 28, 18, 33, 42, 442759)),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 28, 18, 33, 42, 442759)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 28, 18, 33, 42, 441718)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 28, 18, 33, 42, 441718)),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=10)),
                ('name', models.CharField(default='', max_length=255)),
                ('um', models.CharField(default='', max_length=10)),
                ('vat', models.IntegerField(default=0, max_length=2)),
                ('type', models.CharField(default='', max_length=100)),
                ('current_stock', models.IntegerField(default=0, max_length=1000)),
                ('sales_price', models.IntegerField(default=0)),
                ('sales_price_vat', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 28, 18, 33, 42, 442759))),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 28, 18, 33, 42, 442759))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Nomenclator articole',
                'ordering': ['created_at'],
            },
        ),
    ]
