# Generated by Django 4.0.1 on 2022-02-28 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_suppliers_and_clients', '0003_alter_chartofaccount_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 28, 18, 34, 19, 490768)),
        ),
        migrations.AlterField(
            model_name='article',
            name='current_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 28, 18, 34, 19, 490768)),
        ),
        migrations.AlterField(
            model_name='article',
            name='vat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 28, 18, 34, 19, 490768)),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 28, 18, 34, 19, 490768)),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 28, 18, 34, 19, 490768)),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 28, 18, 34, 19, 490768)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 28, 18, 34, 19, 488766)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 28, 18, 34, 19, 488766)),
        ),
    ]
